name: Publish to PyPI

on:
  release:
    types: [published]  # This triggers the workflow when you publish a release on GitHub

permissions:
  id-token: write  # Required for Trusted Publishing to work
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade build

      - name: Build the package
        run: |
          python -m build  # Creates dist/*.whl and dist/*.tar.gz

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
